language: java
jdk:
- oraclejdk8
sudo: required
env:
  global:
  - secure: AZ8WQKphOiKawCAYWamVrcm/jilNAX+nawovfOBADYeqFvbBFycvK1XVhBlSHCCUciuL6nTrh1t5BpB2G+6z9jhjKbNXCu6oauOAACxmg7w3ZDjgMUPYYMHgHbUrIhl2wDYQBVKXR8iQ4tCqm/flzxCap2uBWJX6kh07uTPk8uO6d3uh1jP0Mf0d8sKN9OEIcD3bHbq08EzDueH/iHiqyq5PG8NMLsF9QkKm/78DvL3z0f8Fv2YO/xTKeXEY+yqFc2AOSec7PAavfRAvS2HDc3FLccTNXTjcAEzj8RCMp4kGxwgrC/QyRNpRNlj+MS2lGO5TMYZubpJxq2WdGh0dNMzn7O/Y1E+SrQzIVQkLoUwj8eqexXF3eTOFn5+oYUvmZ67NhfEgorWo045Sci97TzfQcz6TeOtUEQg9rYC2wEB6ygNCZZZkiRAiwkd/kQISaGgW5sdYrP3lrJ5bTiANMOOzOFK0OwecWkQvGCajazw91D+E7pk31aCzl46hp1XR9jVhLQXHb/ymn3B5gE8syN5YYbrQ/cIau+yYkXaTw1lbuPBmOHJeFOr570as7yfIxC2migvqT240wnCDef0fCulZWxey2vRBhop9hUENaIJdV0PmVDMISCa+2xUugWOzbsLrUMnG9sbvj8hqQC8Jw9M3//SW0zD/DoUjDa0IqV4=
  - secure: oqRJ5u+gIRywkSLU0iUEcMMLsyv3/O6kvkYzblWFEo8Y1Lgtzm+snW/i5jF7VHaXAOito/xS33mb1o2++Nfy4w1/fauP+zeT3bfyUuApcTmO3lGDqSqHohKTCN4YiesD5BefFru3+E8ljsg4O1eBoOKSrJsxatlESTktjtqi+PQRvWImhFJEokjxcZleZrBQWBzcRZDOc6XPqPRpmHyOuuTahaYHLVjt2iMd3NNTfAF/MM6OfFRzAod9kozK3j95fRStjiEFAUM5XIEdXGznPxo88K0qtfkbMOsQrWuDeTIqNy8FeBaJm3DM0r9wbJWzWnFKP/wNsjfNEUKoSd7NWFBwRR90wG0dCYwysEmuZT6ROb6+eHIBVYiKT0Hv6/PgQYQUMwxwa52nYbtBh7vh8+NK+pwbC+yvbalulvhgZ1c6+gqWmEZTppFLosdZAnztmNHMkwhdZpVKcurkj76bau4Q+T5f8Qujp7J6mGMcn4v2a55PsvKxLJDPwkMHJt/L8VY0WAeyaMREI7mmhBpxRYY0vEzXtBPC2+TQPZP8VaQzwVmB+wf2SZJxuPPRZyC20kF1ZVaABNWxC2C/Nq0xX6MBga3V1d09MVA2dHL2gWvUXPCfk1CiqqwNHMyCdTO9JB1sd2QwMYgyRWiovFJbQlV6XpmToiDqukRar8GqwQY=
script: gradle clean check runTestNGTestCases -Psuites=TestNgSuiteCampaign.xml -PprimaryUserName=Aldo.Balderrama@mydomain.org -PprimaryUserPassword="$PRIMARY_USER_PASSWORD" -PremoteUserName=mabalderramav -PremoteKey="$REMOTE_KEY"
branches:
only: develop
notifications:
  email: true
  recipients:
  - carlos.gonzales@jalasoft.com
  - AT01@fundacion-jala.org


